const MODAL_STACK = 'MODAL_STACK';

const NOTIFICATIONS = 'NOTIFICATIONS_MODAL';
const NOTIFICATION_SETTINGS = 'NOTIFICATION_SETTINGS_MODAL';


export default {
    MODAL_STACK,
    NOTIFICATIONS,
    NOTIFICATION_SETTINGS
};
